<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net6.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Quartz" Version="3.8.0" />
    <PackageReference Include="SSH.NET" Version="2023.0.0" />
    <PackageReference Include="System.Data.SqlClient" Version="4.9.0" />
    <PackageReference Include="EPPlus" Version="4.5.3.3" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\JKPS.BLL\JKPS.BLL.csproj" />
    <ProjectReference Include="..\JKPS.DL\JKPS.DL.csproj" />
  </ItemGroup>

</Project>
